name: {{ cookiecutter.project_slug }}
channels:
  - conda-forge
dependencies:
  - python=3.10  # Adjust to your Python version
  - pip
  - notebook
  - ipykernel
  - pip:
      - -e ../  # Add your local package
