# Examples install packages in different ways

## Example with packer: https://developer.hashicorp.com/packer/install
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html
- name: Add hashicorp key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  become: true

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html
- name: Add hashicorp repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    filename: /etc/apt/sources.list.d/hashicorp.list
    state: present
  become: true

- name: Install packer
  ansible.builtin.package:
    name: packer
    state: present
    update_cache: true
  become: true